ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# mavros for ros-humble
RUN apt-get update && apt-get install -y \
    ros-humble-mavros  \
    ros-humble-mavros-extras \
    ros-humble-mavros-msgs \
    ros-humble-rqt-common-plugins \
    ros-humble-rqt-tf-tree \
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean

RUN mkdir -p /opt/mavros/
RUN pip install xacro
RUN /opt/ros/${ROS_DISTRO}/lib/mavros/install_geographiclib_datasets.sh